name: microshaft
description: Get logged in to a minecraft account quickly without all of the boilerplate of dancing with microsoft, xbox and mojang servers, maintaining a cache for expiring tokens and whatnot.
version: 1.0.1
repository: https://github.com/cyberpwnn/microshaft
environment:
  sdk: ^3.10.7
dependencies:
  http: ^1.6.0
  json_serializable: ^6.5.1
  json_annotation: ^4.7.0
dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.3.0
